Repository estacaoespacialpirata/space-station-14, pull requests merged in 2022-10, with the labels that each got.

#20 Pudim2
  Resources/Locale/en-US/estacao-pirata/entities/objects/consumable/food/burger.ftl
  Resources/Locale/en-US/estacao-pirata/flavors/flavor-profiles.ftl
  Resources/Prototypes/EstacaoPirata/Cooking/meal_recipes.yml
  Resources/Prototypes/EstacaoPirata/Entities/Objects/Consumable/Food/pudding.yml
  Resources/Prototypes/EstacaoPirata/Flavors/flavors.yml
  Resources/Textures/EstacaoPirata/Objects/Consumable/Food/pudding.rsi/meta.json
  Resources/Textures/EstacaoPirata/Objects/Consumable/Food/pudding.rsi/plate-tart.png
  Resources/Textures/EstacaoPirata/Objects/Consumable/Food/pudding.rsi/pudding.png
  Resources/Textures/EstacaoPirata/Objects/Consumable/Food/pudding.rsi/puddingchoco.png
  Resources/Textures/EstacaoPirata/Objects/Consumable/Food/pudding.rsi/pudim chocolate.png
  Resources/Textures/EstacaoPirata/Objects/Consumable/Food/pudding.rsi/pudim chocolate2.png
  Resources/Textures/EstacaoPirata/Objects/Consumable/Food/pudding.rsi/pudim chocolate3.png
  Resources/Textures/EstacaoPirata/Objects/Consumable/Food/pudding.rsi/pudim chocolate4.png
  Resources/Textures/EstacaoPirata/Objects/Consumable/Food/pudding.rsi/pudim normal.png
  Resources/Textures/EstacaoPirata/Objects/Consumable/Food/pudding.rsi/pudimcomum.png
Labels: No C#, Changes: Sprites

#28 Pirata - ajustes nos rolês e nos timers dos rolês
  Resources/Locale/en-US/connection-messages.ftl
  Resources/Locale/en-US/info/rules.ftl
  Resources/Locale/en-US/reagents/meta/consumable/food/ingredients.ftl
  Resources/Maps/salvage.yml
  Resources/Maps/test.yml
  Resources/Prototypes/EstacaoPirata/Entities/Mobs/NPCs/gianttarantula.yml
  Resources/Prototypes/EstacaoPirata/Entities/Mobs/NPCs/mutants.yml
  Resources/Prototypes/EstacaoPirata/Entities/Objects/Misc/web.yml
  Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
  Resources/Prototypes/Roles/Jobs/Civilian/bartender.yml
  Resources/Prototypes/Roles/Jobs/Civilian/chef.yml
  Resources/Prototypes/Roles/Jobs/Civilian/clown.yml
  Resources/Prototypes/Roles/Jobs/Civilian/janitor.yml
  Resources/Prototypes/Roles/Jobs/Civilian/mime.yml
  Resources/Prototypes/Roles/Jobs/Civilian/musician.yml
  Resources/Prototypes/Roles/Jobs/Civilian/service_worker.yml
  Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
  Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
  Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
  Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
  Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
  Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
  Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
  Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
  Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
  Resources/Prototypes/Roles/Jobs/Wildcards/boxer.yml
Labels: No C#, Changes: Map

#30 tradução de gases.ftl
  Resources/Locale/en-US/gases/gases.ftl
Labels: No C#
