Repository estacaoespacialpirata/space-station-14, pull requests merged in 2022-09, with the labels that each got.

#3 Traduzida a nova atualização
  Resources/Locale/en-US/armor/armor-examine.ftl
  Resources/Locale/en-US/clothing/clothing-speed.ftl
  Resources/Locale/en-US/commands/zoom-command.ftl
  Resources/Locale/en-US/damage/damage-examine.ftl
  Resources/Locale/en-US/flavors/flavor-profiles.ftl
Labels: No C#

#5 Update materials.ftl
  Resources/Locale/en-US/materials/materials.ftl
Labels: No C#

#4 Add: flavor da caipirinha
  Resources/Locale/en-US/estacao-pirata/flavors/flavor-profiles.ftl
  Resources/Prototypes/EstacaoPirata/Flavors/flavors.yml
  Resources/Prototypes/EstacaoPirata/Reagents/Consumable/Drinks/alcohol.yml
  Resources/Prototypes/Flavors/flavors.yml
Labels: No C#

#7 Update tiles.ftl
  Resources/Locale/en-US/tiles/tiles.ftl
Labels: No C#

#6 Simples medibot 2 linhas
  Resources/Locale/en-US/npc/medibot.ftl
Labels: No C#

#8 Feat: Homem camarão
  Resources/Audio/EstacaoPirata/Voice/Prawn/prawn_scream.ogg
  Resources/Prototypes/EstacaoPirata/Body/Mechanisms/prawn.yml
  Resources/Prototypes/EstacaoPirata/Body/Parts/prawn.yml
  Resources/Prototypes/EstacaoPirata/Body/Presets/prawn.yml
  Resources/Prototypes/EstacaoPirata/Cooking/meal_recipes.yml
  Resources/Prototypes/EstacaoPirata/Datasets/Names/prawn.yml
  Resources/Prototypes/EstacaoPirata/Entities/Clothing/Head/misc.yml
  Resources/Prototypes/EstacaoPirata/Entities/Markers/Spawners/ghost_roles.yml
  Resources/Prototypes/EstacaoPirata/Entities/Mobs/NPCs/prawn.yml
  Resources/Prototypes/EstacaoPirata/Entities/Objects/Consumable/Food/meat.yml
  Resources/Textures/EstacaoPirata/Clothing/Head/Misc/cthulhu.rsi/equipped-HELMET.png
  Resources/Textures/EstacaoPirata/Clothing/Head/Misc/cthulhu.rsi/icon.png
  Resources/Textures/EstacaoPirata/Clothing/Head/Misc/cthulhu.rsi/inhand-left.png
  Resources/Textures/EstacaoPirata/Clothing/Head/Misc/cthulhu.rsi/inhand-right.png
  Resources/Textures/EstacaoPirata/Clothing/Head/Misc/cthulhu.rsi/meta.json
  Resources/Textures/EstacaoPirata/Mobs/Animals/prawn.rsi/crit.png
  Resources/Textures/EstacaoPirata/Mobs/Animals/prawn.rsi/dead.png
  Resources/Textures/EstacaoPirata/Mobs/Animals/prawn.rsi/icon.png
  Resources/Textures/EstacaoPirata/Mobs/Animals/prawn.rsi/meta.json
  Resources/Textures/EstacaoPirata/Mobs/Animals/prawn.rsi/prawn.png
  Resources/Textures/EstacaoPirata/Mobs/Animals/prawn.rsi/wounded.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/appendix-inflamed.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/appendix.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/brain-inhand-left.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/brain-inhand-right.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/brain.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/ears.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/eyeball-l.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/eyeball-r.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/heart-off.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/heart-on.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/kidney-l.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/kidney-r.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/liver.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/lung-l.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/lung-r.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/meta.json
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/muscle.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/nerve.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/stomach.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/tongue.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/organs.rsi/vessel.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/parts.rsi/full.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/parts.rsi/head_f.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/parts.rsi/head_m.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/parts.rsi/l_arm.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/parts.rsi/l_foot.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/parts.rsi/l_hand.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/parts.rsi/l_leg.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/parts.rsi/meta.json
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/parts.rsi/r_arm.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/parts.rsi/r_foot.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/parts.rsi/r_hand.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/parts.rsi/r_leg.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/parts.rsi/torso_f.png
  Resources/Textures/EstacaoPirata/Mobs/Species/Prawn/parts.rsi/torso_m.png
  Resources/Textures/EstacaoPirata/Objects/Consumable/Food/meat.rsi/meta.json
  Resources/Textures/EstacaoPirata/Objects/Consumable/Food/meat.rsi/plate-meat.png
  Resources/Textures/EstacaoPirata/Objects/Consumable/Food/meat.rsi/shrimp-cooked.png
  Resources/Textures/EstacaoPirata/Objects/Consumable/Food/meat.rsi/shrimp.png
Labels: No C#, Changes: Sprites

#11 PR TESTE TRADUÇÃO PEQUENA
  Resources/Locale/en-US/administration/admin-verbs.ftl
  Resources/Locale/en-US/administration/antag.ftl
  Resources/Locale/en-US/administration/commands/add-uplink-command.ftl
  Resources/Locale/en-US/administration/ui/set-outfit/set-outfit-menu.ftl
Labels: No C#

#13 Glacier Station
  Resources/Maps/glacier.yml
  Resources/Prototypes/Maps/glacier.yml
Labels: No C#, Changes: Map

#17 ADD: receita de hamburger de rato e tradução do xratão
  Resources/Locale/en-US/estacao-pirata/Prototypes/Entities/Objects/Consumable/Food/burger.ftl
  Resources/Prototypes/EstacaoPirata/Cooking/meal_recipes.yml
Labels: No C#

#18 Cacau
  Resources/Locale/en-US/crayon/crayon-component.ftl
  Resources/Prototypes/Catalog/Fills/Crates/botany.yml
  Resources/Prototypes/EstacaoPirata/Entities/Objects/Consumable/Food/produce.yml
  Resources/Prototypes/EstacaoPirata/Entities/Objects/Specific/Hydroponics/seeds.yml
  Resources/Prototypes/EstacaoPirata/Hydroponics/seeds.yml
  Resources/Textures/EstacaoPirata/Objects/Specific/Hydroponics/cacao.rsi/dead.png
  Resources/Textures/EstacaoPirata/Objects/Specific/Hydroponics/cacao.rsi/harvest.png
  Resources/Textures/EstacaoPirata/Objects/Specific/Hydroponics/cacao.rsi/meta.json
  Resources/Textures/EstacaoPirata/Objects/Specific/Hydroponics/cacao.rsi/produce.png
  Resources/Textures/EstacaoPirata/Objects/Specific/Hydroponics/cacao.rsi/seed.png
  Resources/Textures/EstacaoPirata/Objects/Specific/Hydroponics/cacao.rsi/stage-1.png
  Resources/Textures/EstacaoPirata/Objects/Specific/Hydroponics/cacao.rsi/stage-2.png
  Resources/Textures/EstacaoPirata/Objects/Specific/Hydroponics/cacao.rsi/stage-3.png
  Resources/Textures/EstacaoPirata/Objects/Specific/Hydroponics/cacao.rsi/stage-4.png
  Resources/Textures/EstacaoPirata/Objects/Specific/Hydroponics/cacao.rsi/stage-5.png
  Resources/Textures/EstacaoPirata/Objects/Specific/Hydroponics/cacao.rsi/stage-6.png
Labels: No C#, Changes: Sprites
